# https://taskfile.dev

version: "3"

tasks:
  validate:
    desc: Validate the pre-commit hooks
    cmds:
      - pre-commit install
      - pre-commit run -a

  test:
    desc: Run automated tests
    cmds:
      - go test

  secure:
    desc: Run automated security checks
    cmds:
      - echo "TODO: Add security scans"

  deliver:
    desc: Deliver artifact
    cmds:
      - echo "Add your logic here"
      - exit 1

  deploy:
    desc: Deploy project
    cmds:
      - echo "N/A. This project doesn't deploy."
