# https://taskfile.dev

version: "3"

tasks:
  validate:
    desc: Validate the pre-commit hooks
    cmds:
      - pre-commit install
      - pre-commit run -a

  test:
    desc: Run automated tests
    cmds:
      - go test ./... -cover

  testReport:
    desc: Open an HTML test report with coverage metrics
    vars:
      COVERPROFILE: coverprofile.tmp
    cmds:
      - go test -coverprofile={{.COVERPROFILE}} ./... && go tool cover -html={{.COVERPROFILE}} && rm {{.COVERPROFILE}}

  secure:
    desc: Run automated security checks
    cmds:
      - echo "TODO: Add security scans"

  deliver:
    desc: Deliver artifact
    vars:
      GITHUB_TOKEN: '{{ coalesce .GITHUB_TOKEN "<no value>" }}'
    preconditions:
      - sh: test "{{.GITHUB_TOKEN}}" != "<no value>"
        msg: Required variable 'GITHUB_TOKEN' not set
    cmds:
      - goreleaser --rm-dist

  deploy:
    desc: Deploy project
    cmds:
      - echo "N/A. This project doesn't deploy."
